### ISSUE TITLE
Merhaba

### ISSUE THREAD

**Issue by krall5759** [bkrucarci/turk-adlist#11]
Merhaba öncelikle bu adlist için sizlere çok teşekkür ediyorum.Nextdns üzerinden bu adlisti ekleme yaptığım zaman acunn.com ve tv8 in sitesinde canlı yayın ve videoları izleyemiyorum ne zaman bu adlist i kaldırınca videolar açılıyor adlist içerisindeki tv8 ve acunn.com ile ilgili olan kısımları beyazlisteye ekledim ama düzelmedi yardımcı olabilir misiniz ?
İlk defa github kullanıyorum umarım yanlış yere yazı yazmamışımdır şimdiden teşekkür ediyorum.

**Comment by bkrucarci** [comment]
Merhaba,
Listeyi kullandığınız için ben teşekkür ederim. Listenin yapısı (host) gereği bu tarz sorunlar olabiliyor. acunn.com üzerindeki sorunu çözdüm ancak tv8 canlı yayınının çalışabilmesi için silmem gereken kuralı silersem birçok siteyi etkileyecek. Yalnızca tv8 üzerinde çözebileceğim bir sorun değil maalesef. Reklam engellemenin önüne geçmek için bunu yapıyorlar. Maalesef  bahsettiğim kısıtlamadan dolayı TV8 canlı yayınındaki sorunu çözemiyorum. TV8 canlı yayınını 'www.ecanlitvizle.live' benzeri sitelerden benim listem aktif iken rahatça izleyebilirisiniz. Alternatif çözüm önerimdir. Filtreyi güncelleyip kullanmaya devam ediniz. İyi günler.

**Comment by krall5759** [comment]
İlgi alakanız için tekrardan çok teşekkür ederim sağolun varolun
