### ISSUE TITLE
YouTube Vanced'i Sil

### ISSUE THREAD

**Issue by Mennaruuk** [bkrucarci/turk-adlist#27]
Harika bir program artık öldü.
https://www.androidpolice.com/google-finally-succeeds-in-killing-youtube-vanced

**Comment by Mennaruuk** [comment]
Biliyorum! üzüntünüzü paylaşıyorum. Bu korkunç bir gün. Yine de bu geliştiricileri suçlamıyorum. Trilyon dolarlık bir şirketle karşı karşıyalar, şansları çok az. Keşke anonimleşmek için adımlar atsalar ama artık çok geçti. Bu geliştiricilerin çalışmaları için minnettarım.

**Comment by bkrucarci** [comment]
> Biliyorum! üzüntünüzü paylaşıyorum. Bu korkunç bir gün. Yine de bu geliştiricileri suçlamıyorum. Trilyon dolarlık bir şirketle karşı karşıyalar, şansları çok az. Keşke anonimleşmek için adımlar atsalar ama artık çok geçti. Bu geliştiricilerin çalışmaları için minnettarım.

They should release the source code of the app. Make the code open then leave it to people. Maybe someone will use it later for another alternative without the name of YouTube.

**Comment by Mennaruuk** [comment]
I agree 100%. I think it's too late. There was an opportunity to open-source it for years, but they had good reasons not to open source it: it's a mod of a proprietary app, it would have made Google come at them earlier. At this point they will get suspected of releasing it into the wild if the app gets open sourced, and they wouldn't want trouble. Very sad. What a cool app.

**Comment by bkrucarci** [comment]
Thanks @Mennaruuk for reporting it. I'll update the README.
