### ISSUE TITLE
traffic.libsyn.com blocks audio on developeronfire.com

### ISSUE THREAD

**Issue by eaglerob** [bkrucarci/turk-adlist#3]
Filter traffic.libsyn.com blocks audio on  [http://developeronfire.com/](http://developeronfire.com/podcast/episode-308-jose-gonzalez-mind-body-soul)

**Comment by bkrucarci** [comment]
Thanks for reporting, the rule deleted! https://github.com/bkrucarci/turk-adlist/commit/ec99fe55134f0c698f8260d212ddbdb36c11e4d6
