### ISSUE TITLE
hata

### ISSUE THREAD

**Issue by muzikherif** [bkrucarci/turk-adlist#32]
bloomberght.com da bazı resimler yüklenmiyor, ayrıca el atmışken aynı sitede çerez uyarısını da kaldırabilirseniz iyi olur

**Comment by bkrucarci** [comment]
> bloomberght.com da bazı resimler yüklenmiyor, ayrıca el atmışken aynı sitede çerez uyarısını da kaldırabilirseniz iyi olur

Merhaba,
Sorunu bildirdiğiniz için teşekkürler. Hatalı engellemeyi giderdim. Listenin yapısı "host" olduğu için içerik engelleme işlemi çok kısıtlıdır. İyi günler

**Comment by muzikherif** [comment]
teşekkürler
