### ISSUE TITLE
Banka Uygulamaları Sorunları

### ISSUE THREAD

**Issue by volkanustabas** [bkrucarci/turk-adlist#33]
Merhaba,

**127.0.0.1 analytics.halkbank.com.tr
127.0.0.1 mark.isbank.com.tr**

Bu iki satır ekli olduğu için ilgili mobile applerde bazı sorunlar oluyor. Sizin listenizi kaldırdığımda sorun kalmıyor. (nextdns)
Listenizi kullanmaya devam etmek istiyorum. Mümkün ise banka ile ilgili engellemeyi kaldırabilir misiniz ?

**Comment by bkrucarci** [comment]
@volkanustabas Sorunlu kuralları sildim. Bildiriminiz için teşekkürler. S
