### ISSUE TITLE
A101 sitesinde analitik

### ISSUE THREAD

**Issue by gork7777** [bkrucarci/turk-adlist#38]
Filtreleme günlüğünde buna bakar mısın? `||ayb.akinoncdn.com/static_omnishop/ayb828/`
Websitesi: [A101](https://www.a101.com.tr/)

**Comment by bkrucarci** [comment]
Merhaba  @gork7777 :) Nasılsın?

Bahsettiğin domainden kayar menüdeki fotoğrafları ve gifleri de çekiyor. Kullanıcıyı takip ediyor olsa bile engellememiz durumunda siteyi bozacaktır. Blldirim için teşekkürler.

**Comment by gork7777** [comment]
Merhaba @bkrucarci iyiyim şükür iş güç. Sen nasılsın?

**Comment by bkrucarci** [comment]
> Merhaba @bkrucarci iyiyim şükür iş güç. Sen nasılsın?

Al benden de o kadar. Yoğun çalışma süreci içindeyim son 1 yldır. Daha da yoğunlaşıyor. Kolaylıklar diliyorum sana da :) Kendine çok dikkat et :)

**Comment by gork7777** [comment]
Yorma kendini fazla dikkatli ol kendi işinde ve teşekkür ederim :)
