### ISSUE TITLE
Yeni url ekleme

### ISSUE THREAD

**Issue by methicodx** [bkrucarci/turk-adlist#39]
Merhaba,

https://www.usom.gov.tr/url-list.txt 

Bu listedeki alan adları zararlı olarak tespit edilmiş. Listeye eklemeniz mümkünse eğer, çok faydalı olur.

Teşekkürler,

**Comment by furkun** [comment]
NextDNS ile harici filtreler ekleyemiyoruz, bu listeye dahil edilmesi durumunda kullanabiliriz. Mükemmel olur, teşekkürler.

**Comment by ensarisik** [comment]
@bkrucarci

**Comment by bkrucarci** [comment]
Merhaba @methicodx ve @furkun 
Bu listeyi oluşturma amacım reklam engelleme konusunda farkındalık oluşturmaktır. 
Eklenmesini sitediğiniz alan adları daha çok güvenlik odaklı gibi görünüyor. Listeye eklemeyi düşünmüyorum.
Teklifiniz için teşekkür ederim.
