### ISSUE TITLE
nativespot.com

### ISSUE THREAD

**Issue by PentagramTr** [bkrucarci/turk-adlist#4]
Webrazzi sitesi `Adrazzi ` olan reklam sunucusunun ismini `NativeSpot ` olarak değiştirmiş.
Bunu da ekleyebilir misiniz?

Detaylar için link
https://webrazzi.com/2018/04/11/nativespot-dogal-reklam-servisimiz-adrazzi-modelini-ve-ismini-degistiriyor/

**Comment by PentagramTr** [comment]
AdGuard kuralı

https://github.com/AdguardTeam/AdguardFilters/blob/f9a445bc5a5651b833ffc66f2324cc7fe254ca70/TurkishFilter/sections/adservers.txt#L2

**Comment by bkrucarci** [comment]
Merhaba @PentagramTr 
Güncelleme ile ekledim. Teşekkürler
https://github.com/bkrucarci/turk-adlist/commit/a5cdb014ec861dc8961211d7f520400717011ead
