### ISSUE TITLE
adl.mynetreklam.com

### ISSUE THREAD

**Issue by PentagramTr** [bkrucarci/turk-adlist#5]
Mynet.com sitesinde rastladığım bir reklam sunucusu.Gerekiyorsa listenize ekler misiniz?.
Detaylar 
https://github.com/AdguardTeam/AdguardFilters/issues/16615

`adl.mynetreklam.com`

**Comment by bkrucarci** [comment]
Merhaba @PentagramTr 
Güncelleme ile ekledim. Teşekkürler
https://github.com/bkrucarci/turk-adlist/commit/a5cdb014ec861dc8961211d7f520400717011ead
