### ISSUE TITLE
Performance Native

### ISSUE THREAD

**Issue by PentagramTr** [bkrucarci/turk-adlist#6]
Sanırım bu bir reklam ağı.İlk olarak Yeni Alanya sitesi üzerinde gördüm.

https://www.yenialanya.com/turizm/turistler-oktoberfest-i-kutladi-h339716.html

<details><summary>Screenshot:</summary>

![www yenialanya com](https://user-images.githubusercontent.com/34379403/46974663-5653b680-d0cd-11e8-850e-59d75ae29713.png)

</details>
<br />

Resmi site
http://performancenative.com/

**Comment by PentagramTr** [comment]
https://github.com/AdguardTeam/AdguardFilters/commit/23ae170630531cd847e69b3d8ccf8219fa3723f5

**Comment by bkrucarci** [comment]
Merhaba @PentagramTr 
Güncelleme ile ekledim. Teşekkürler
https://github.com/bkrucarci/turk-adlist/commit/a5cdb014ec861dc8961211d7f520400717011ead
