### ISSUE TITLE
Spotify Sorunu

### ISSUE THREAD

**Issue by ozdemibr** [bkrucarci/turk-adlist#7]
Kendi vpn sunucum için çeşitli adblock listelerini dnsmasq ile kullanmaktayım. İçlerinde senin listen de var. Fakat senin listende spotify domaini de blokluyorsun. Scriptle çözebilirim fakat kaldırılması diğer kullanıcılar için de faydalı olacaktır.

Teşekkürker liste için.

127.0.0.1 adeventtracker.spotify.com
127.0.0.1 ads-fa.spotify.com
127.0.0.1 analytics.spotify.com
127.0.0.1 audio2.spotify.com
127.0.0.1 crashdump.spotify.com
127.0.0.1 desktop.spotify.com
127.0.0.1 log.spotify.com
127.0.0.1 open.spotify.com
127.0.0.1 spclient.wg.spotify.com
127.0.0.1 weblb-wg.gslb.spotify.com

**Comment by bkrucarci** [comment]
Olası tüm sorunları da çözmek adına Spotify ile tüm satırları temizledim. Vakit ayırıp yazdığınız için teşekkür ederim.
